table "../text_table.txt"

option_title:
		db "     YELLOW SWITCH BLOCKS       "
		db "     GREEN SWITCH BLOCKS        "
		db "     RED SWITCH BLOCKS          "
		db "     BLUE SWITCH BLOCKS         "
		db "     SPECIAL WORLD EFFECTS      "
		db "     MARIO POWERUP STATUS       "
		db "     ITEM IN RESERVE BOX        "
		db "     YOSHI COLOR                "
		db "     RESET ENEMY STATES         "
		db "     DELETE SAVE DATA           "
		db "     SPRITE SLOT NUMBERS        "
		db "     SECOND CONTROLLER          "
		db "     PAUSE BUFFER               "
		db "     TIME UP DEATH              "
		db "     MUSIC                      "
		db "     HOTKEY INTERFERENCE        "
		db "     SAVE STATES                "
		db "     SAVE STATE DELAY           "
		db "     DYNAMIC METER DISPLAY      "
		db "     SLOW MOTION                "
		db "     HELP                       "
		db "     L-R RESET                  "
		db "     MEMORY VIEWER HIGH BYTE    "
		db "     MEMORY VIEWER LOW BYTE     "
		db "     SAVE MOVIE TO S-RAM        "
		db "     LOAD MOVIE                 "
		db "     PLAYER NAME                "
		db "     PLAYER NAME                "
		db "     PLAYER NAME                "
		db "     PLAYER NAME                "
		db "     REGION                     "

option_description:
		db "  TURN THE YELLOW               "
		db "  SWITCH PALACE BLOCKS          "
		db "  ON OR OFF                     "
		db "                                "
		db "                                "
		db "                                "
		db "  TURN THE GREEN                "
		db "  SWITCH PALACE BLOCKS          "
		db "  ON OR OFF                     "
		db "                                "
		db "                                "
		db "                                "
		db "  TURN THE RED                  "
		db "  SWITCH PALACE BLOCKS          "
		db "  ON OR OFF                     "
		db "                                "
		db "                                "
		db "                                "
		db "  TURN THE BLUE                 "
		db "  SWITCH PALACE BLOCKS          "
		db "  ON OR OFF                     "
		db "                                "
		db "                                "
		db "                                "
		db "  TOGGLE THE VARIOUS EFFECTS    "
		db "  THAT OCCUR WHEN SPECIAL       "
		db "  WORLD IS COMPLETED            "
		db "  SUCH AS DIFFERENT             "
		db "  KOOPA SHELL COLORS            "
		db "                                "
		db "  PICK WHICH POWERUP            "
		db "  MARIO CURRENTLY HAS           "
		db "                                "
		db "                                "
		db "                                "
		db "                                "
		db "  PICK WHAT ITEM IS CURRENTLY   "
		db "  IN THE ITEM RESERVE BOX       "
		db "                                "
		db "                                "
		db "                                "
		db "                                "
		db "  PICK WHAT COLOR OF YOSHI      "
		db "  MARIO IS CURRENTLY RIDING     "
		db "                                "
		db "                                "
		db "                                "
		db "                                "
		db "  REINITIALIZE ENEMIES THAT     "
		db "  REMEMBER THE LAST STATE       "
		db "  THAT THEY WERE IN             "
		db "  SUCH AS BOO CLOUDS            "
		db "  AND BOO RINGS                 "
		db "                                "
		db "  REMOVE ALL SAVED DATA         "
		db "  OR JUST SAVED TIMES FOR       "
		db "  THE LEVEL MARIO IS CURRENTLY  "
		db "  STANDING ON OR ONLY A         "
		db "  PARTICULAR SAVED TIME         "
		db "                                "
		db "  DISPLAY WHICH SLOT            "
		db "  EACH SPRITE IS CURRENTLY      "
		db "  SPAWNED WITHIN                "
		db "                                "
		db "                                "
		db "                                "
		db "  DISABLE CONTROLLER 2          "
		db "  OR ALLOW IT TO ONLY CONTROL   "
		db "  MARIO OR ALLOW IT TO          "
		db "  CONTROL ANYTHING              "
		db "                                "
		db "                                "
		db "  TOGGLE THE BUFFER TIME        "
		db "  IN BETWEEN SUCCESSIVE         "
		db "  PAUSING                       "
		db "                                "
		db "                                "
		db "                                "
		db "  TOGGLE THE HURRY UP SOUND     "
		db "  AND TIME UP DEATH             "
		db "                                "
		db "                                "
		db "                                "
		db "                                "
		db "  TOGGLE THE BACKGROUND MUSIC   "
		db "                                "
		db "                                "
		db "                                "
		db "                                "
		db "                                "
		db "  DISABLE THE START AND         "
		db "  SELECT BUTTONS WHILE          "
		db "  L OR R ARE BEING HELD         "
		db "  TO RESOLVE SOME               "
		db "  FUNCTIONALITY CONFLICT        "
		db "                                "
		db "  USE R-SELECT TO CREATE        "
		db "  A SAVE STATE AND THEN         "
		db "  USE L-SELECT TO RELOAD        "
		db "  THAT STATE                    "
		db "                                "
		db "                                "
		db "  PICK HOW QUICKLY              "
		db "  IT TAKES FOR A                "
		db "  SAVE STATE TO LOAD            "
		db "                                "
		db "                                "
		db "                                "
		db "  SHOW INFORMATION ABOUT        "
		db "  AN OBJECT THAT FOLLOWS        "
		db "  IT AS IT MOVES AROUND         "
		db "  SUCH AS SPEED OR              "
		db "  SUBPIXEL VALUES               "
		db "                                "
		db "  USE R-START TO GRADUALLY      "
		db "  INCREASE THE SLOWDOWN         "
		db "  EFFECT AND USE L-START        "
		db "  TO RETURN TO NORMAL SPEED     "
		db "                                "
		db "                                "
		db "  DISPLAY INFORMATION ABOUT     "
		db "  WHAT EVERYTHING IN THE        "
		db "  STATUS BAR AND OVERWORLD      "
		db "  HUD REPRESENTS                "
		db "                                "
		db "                                "
		db "  USE L-R TO RESET THE CURRENT  "
		db "  ROOM AND A-B-L-R TO RESET     "
		db "  THE ENTIRE LEVEL AND          "
		db "  X-Y-L-R TO ADVANCE ONE ROOM   "
		db "                                "
		db "                                "
		db "  THE MEMORY ADDRESS TO SHOW    "
		db "  IN THE MEMORY VIEWER          "
		db "  THIS IS THE UPPER 8 BITS      "
		db "  FORMAT IS 7EXX--              "
		db "                 RNG = 148D     "
		db "            B5 CLOUD = 00E4     "
		db "  THE MEMORY ADDRESS TO SHOW    "
		db "  IN THE MEMORY VIEWER          "
		db "  THIS IS THE LOWER 8 BITS      "
		db "  FORMAT IS 7E--XX              "
		db "                 RNG = 148D     "
		db "            B5 CLOUD = 00E4     "
		db "  PICK A SAVE SLOT TO SAVE      "
		db "  EXPORT THE CURRENTLY          "
		db "  LOADED MOVIE IN SAVE RAM      "
		db "  TO SHARE WITH OTHERS          "
		db "                                "
		db "                                "
		db "  PICK A SAVE SLOT TO LOAD      "
		db "  A MOVIE FROM SAVE RAM         "
		db "  OR LOAD A DEMO MOVIE          "
		db "  OF THIS LEVEL                 "
		db "                                "
		db "                                "
		db "  YOUR NAME                     "
		db "                                "
		db "                                "
		db "                                "
		db "  OR REALLY WHATEVER TEXT       "
		db "  YOU WANT TO PUT HERE          "
		db "  YOUR NAME                     "
		db "                                "
		db "                                "
		db "                                "
		db "  OR REALLY WHATEVER TEXT       "
		db "  YOU WANT TO PUT HERE          "
		db "  YOUR NAME                     "
		db "                                "
		db "                                "
		db "                                "
		db "  OR REALLY WHATEVER TEXT       "
		db "  YOU WANT TO PUT HERE          "
		db "  YOUR NAME                     "
		db "                                "
		db "                                "
		db "                                "
		db "  OR REALLY WHATEVER TEXT       "
		db "  YOU WANT TO PUT HERE          "
		db "  THIS WILL AFFECT REGION       "
		db "  DIFFERENCES SUCH AS           "
		db "  LEVEL LAYOUT AND              "
		db "  MECHANICS CHANGES             "
		db "                                "
		db "                                "
		
help_title:
		db "     LEVEL TIMER                "
		db "     ROOM TIMER                 "
		db "     LAG FRAME COUNTER          "
		db "     COIN COUNTER               "
		db "     IN GAME TIMER              "
		db "     MEMORY VIEWER              "
		db "     SLOWDOWN RATIO             "
		db "     INPUT DISPLAY              "
		db "     MARIO X SPEED              "
		db "     MARIO TAKEOFF COUNTER      "
		db "     MARIO P METER              "
		db "     YOSHI XY SUBPIXELS         "
		db "     HELD ITEM XY SUBPIXELS     "
		db "     NORMAL EXIT SMALL ONLY     "
		db "     NORMAL EXIT NO CAPE        "
		db "     NORMAL EXIT IN GENERAL     "
		db "     NORMAL EXIT LUNAR DRAGON   "
		db "     SECRET EXIT SMALL ONLY     "
		db "     SECRET EXIT NO CAPE        "
		db "     SECRET EXIT IN GENERAL     "
		db "     SECRET EXIT LUNAR DRAGON   "
		db "     MOVIE CAPACITY             "
		db "     PLAYER NAME                "
		db "     MOVIE AUTHOR               "
		db "     STOPWATCH                  "

help_descriptions:
		db "  TICKS FOR THE ENTIRE          "
		db "  DURATION OF THE LEVEL         "
		db "                                "
		db "                                "
		db "                                "
		db "                                "
		db "  ONLY TICKS FOR THE DURATION   "
		db "  OF THE ROOM YOU ARE IN AND    "
		db "  WILL RESET WHEN YOU ENTER     "
		db "  A PIPE OR DOOR                "
		db "                                "
		db "                                "
		db "  INCREMENTS FOR EVERY FRAME    "
		db "  OF LAG THAT OCCURS DURING     "
		db "  THE CURRENT ROOM              "
		db "  THIS NUMBER IS DISPLAYED      "
		db "  IN HEXADECIMAL                "
		db "                                "
		db "  KEEPS TRACK OF HOW MANY       "
		db "  COINS YOU HAVE COLLECTED      "
		db "  DURING THE LEVEL              "
		db "                                "
		db "                                "
		db "                                "
		db "  KEEPS TRACK OF GAME TIME      "
		db "  THE WHITE NUMBER IS THE       "
		db "  FRACTIONAL SECOND THAT        "
		db "  COUNTS DOWN FROM 40           "
		db "                                "
		db "                                "
		db "  DISPLAYS THE 16-BIT VALUE     "
		db "  STORED AT THE CURRENT         "
		db "  ADDRESS SPECIFIED BY          "
		db "  THE MEMORY VIEWER OPTION      "
		db "                                "
		db "                                "
		db "  DISPLAYS THE CURRENT SPEED    "
		db "  RATIO IF LESS THAN ONE        "
		db "  TWO EQUALS ONE HALF SPEED     "
		db "  THREE EQUALS ONE THIRD        "
		db "  SPEED AND SO ON               "
		db "                                "
		db "  SHOWS THE CURRENTLY PRESSED   "
		db "  BUTTONS ON THE CONTROLLER     "
		db "                                "
		db "                                "
		db "                                "
		db "                                "
		db "  DISPLAYS THE MAGNITUDE        "
		db "  OF MARIOS CURRENT             "
		db "  HORIZONTAL SPEED MEASURED     "
		db "  IN SUBPIXELS PER FRAME        "
		db "                                "
		db "                                "
		db "  DISPLAYS THE NUMBER OF        "
		db "  FRAMES UNTIL CAPED MARIO      "
		db "  WILL STOP FLYING UPWARD       "
		db "  AND BEGIN THE CAPE FLIGHT     "
		db "  ANIMATION                     "
		db "                                "
		db "  SHOWS HOW LONG UNTIL          "
		db "  MARIO WILL START RUNNING      "
		db "  AT FULL SPEED                 "
		db "  THIS COUNTER HAS A            "
		db "  MAXIMUM OF SEVEN              "
		db "                                "
		db "  SHOWS THE VISIBLE YOSHIS      "
		db "  CURRENT X AND Y SUBPIXELS     "
		db "  ONLY SHOWS THE HIGHEST        "
		db "  FOUR BITS SINCE THE LOWEST    "
		db "  FOUR ARE ALWAYS ZERO          "
		db "                                "
		db "  SHOWS THE MOST RECENTLY       "
		db "  HELD ITEMS CURRENT            "
		db "  X AND Y SUBPIXELS             "
		db "  ONLY SHOWS THE HIGHEST        "
		db "  FOUR BITS SINCE THE LOWEST    "
		db "  FOUR ARE ALWAYS ZERO          "
		db "  YOUR BEST TIME COMPLETING     "
		db "  THE NORMAL EXIT WITHOUT       "
		db "  USING POWERUPS OR YOSHI       "
		db "  OR P BALLOONS OR STARS        "
		db "  A TIME IS GOLD IF IT IS       "
		db "  A RESPECTABLE TIME            "
		db "  YOUR BEST TIME COMPLETING     "
		db "  THE NORMAL EXIT WITHOUT       "
		db "  USING A CAPE                  "
		db "  A TIME IS PINK IF IT IS       "
		db "  A NEARLY PERFECT PLAY         "
		db "  THROUGH OF THE LEVEL          "
		db "  YOUR BEST TIME COMPLETING     "
		db "  THE NORMAL EXIT WITH          "
		db "  NO RESTRICTIONS               "
		db "                                "
		db "                                "
		db "                                "
		db "  YOUR BEST TIME COMPLETING     "
		db "  THE NORMAL EXIT WHILE         "
		db "  ALSO COLLECTING AT LEAST      "
		db "  FIVE DRAGON COINS             "
		db "  AND A MOON IF ONE             "
		db "  EXISTS IN THAT LEVEL          "
		db "  YOUR BEST TIME COMPLETING     "
		db "  THE SECRET EXIT WITHOUT       "
		db "  USING POWERUPS OR YOSHI       "
		db "  OR P BALLOONS OR STARS        "
		db "  A TIME IS BLANK IF YOU        "
		db "  HAVENT DONE IT YET            "
		db "  YOUR BEST TIME COMPLETING     "
		db "  THE SECRET EXIT WITHOUT       "
		db "  USING A CAPE                  "
		db "                                "
		db "                                "
		db "                                "
		db "  YOUR BEST TIME COMPLETING     "
		db "  THE SECRET EXIT WITH          "
		db "  NO RESTRICTIONS               "
		db "                                "
		db "                                "
		db "                                "
		db "  YOUR BEST TIME COMPLETING     "
		db "  THE SECRET EXIT WHILE         "
		db "  ALSO COLLECTING AT LEAST      "
		db "  FIVE DRAGON COINS             "
		db "  AND A MOON IF ONE             "
		db "  EXISTS IN THAT LEVEL          "
		db "  WHEN RECORDING A MOVIE        "
		db "  DISPLAYS HOW MUCH SPACE       "
		db "  IS LEFT UNTIL THE MOVIE       "
		db "  IS TOO LARGE TO SAVE          "
		db "                                "
		db "                                "
		db "  YOUR NAME                     "
		db "                                "
		db "                                "
		db "                                "
		db "  OR REALLY WHATEVER TEXT       "
		db "  YOU WANT TO PUT HERE          "
		db "  THE AUTHOR OF THE             "
		db "  CURRENTLY PLAYING MOVIE       "
		db "                                "
		db "                                "
		db "                                "
		db "                                "
		db "  ONLY TICKS WHEN THE GAME      "
		db "  IS NOT PAUSED                 "
		db "  UNPAUSING WILL RESET          "
		db "  THIS TIMER                    "
		db "                                "
		db "                                "